services:
  headscale:
    image: docker.io/headscale/headscale:0.29.3
    restart: unless-stopped
    container_name: headscale
    read_only: true
    tmpfs:
      - /var/run/headscale
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      # Please set <HEADSCALE_PATH> to the absolute path
      # of the previously created headscale directory.
      - /home/ubuntu/headscale/config:/etc/headscale:ro
      - /home/ubuntu/headscale/lib:/var/lib/headscale
    command: serve
    healthcheck:
        test: ["CMD", "headscale", "health"]
